package com.junaldadlawan.event_ticketing_api.waitlist;

import com.junaldadlawan.event_ticketing_api.auth.service.JwtService;
import com.junaldadlawan.event_ticketing_api.common.entity.Money;
import com.junaldadlawan.event_ticketing_api.event.entity.Event;
import com.junaldadlawan.event_ticketing_api.event.enums.EventStatus;
import com.junaldadlawan.event_ticketing_api.event.repository.EventRepository;
import com.junaldadlawan.event_ticketing_api.organization.entity.Organization;
import com.junaldadlawan.event_ticketing_api.organization.enums.OrganizationStatus;
import com.junaldadlawan.event_ticketing_api.organization.repository.OrganizationRepository;
import com.junaldadlawan.event_ticketing_api.tickettype.entity.TicketType;
import com.junaldadlawan.event_ticketing_api.tickettype.enums.TicketTypeKind;
import com.junaldadlawan.event_ticketing_api.tickettype.repository.TicketTypeRepository;
import com.junaldadlawan.event_ticketing_api.user.entity.User;
import com.junaldadlawan.event_ticketing_api.user.enums.Role;
import com.junaldadlawan.event_ticketing_api.user.repository.UserRepository;
import com.junaldadlawan.event_ticketing_api.waitlist.entity.WaitlistEntry;
import com.junaldadlawan.event_ticketing_api.waitlist.repository.WaitlistEntryRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.test.web.servlet.MockMvc;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Full {@code @SpringBootTest} coverage for {@code POST
 * /events/{eventId}/waitlist} and {@code GET /users/me/waitlist-entries}
 * against real Postgres + real signed JWTs. Proves the sold-out gate
 * against real {@code TicketType} rows, the real position sequence across
 * multiple joiners, the new {@code SecurityConfig} matcher's visibility
 * split, and — via a real {@code ExecutorService} race — that concurrent
 * joins for the same (event, ticketType) scope never collide on position
 * (BR-WAIT-001/002, the retry-loop's actual job).
 */
@SpringBootTest
@AutoConfigureMockMvc
class WaitlistIntegrationTest {

    @Autowired
    private MockMvc mockMvc;
    @Autowired
    private JwtService jwtService;
    @Autowired
    private OrganizationRepository organizationRepository;
    @Autowired
    private EventRepository eventRepository;
    @Autowired
    private TicketTypeRepository ticketTypeRepository;
    @Autowired
    private WaitlistEntryRepository waitlistEntryRepository;
    @Autowired
    private UserRepository userRepository;

    private final List<UUID> createdOrgIds = new ArrayList<>();
    private final List<UUID> createdEventIds = new ArrayList<>();
    private final List<UUID> createdTicketTypeIds = new ArrayList<>();
    private final List<UUID> createdUserIds = new ArrayList<>();
    private final List<UUID> createdWaitlistEntryIds = new ArrayList<>();

    @AfterEach
    void tearDown() {
        for (UUID id : createdWaitlistEntryIds) {
            waitlistEntryRepository.deleteById(id);
        }
        createdWaitlistEntryIds.clear();
        // Sweep any entries the concurrency test created that weren't
        // individually tracked (bulk-generated by concurrent joiners).
        waitlistEntryRepository.findAll().stream()
                .filter(e -> createdEventIds.contains(e.getEventId()))
                .forEach(e -> waitlistEntryRepository.deleteById(e.getId()));
        for (UUID id : createdTicketTypeIds) {
            ticketTypeRepository.deleteById(id);
        }
        createdTicketTypeIds.clear();
        for (UUID id : createdEventIds) {
            eventRepository.deleteById(id);
        }
        createdEventIds.clear();
        for (UUID id : createdOrgIds) {
            organizationRepository.deleteById(id);
        }
        createdOrgIds.clear();
        for (UUID id : createdUserIds) {
            userRepository.deleteById(id);
        }
        createdUserIds.clear();
    }

    private User inMemoryUser(Role role) {
        return User.builder().id(UUID.randomUUID()).email(role.name().toLowerCase() + "-" + UUID.randomUUID() + "@test.local").role(role).build();
    }

    private User persistUser(Role role) {
        User user = User.builder()
                .name("Waitlist Test User")
                .email("waitlist-" + UUID.randomUUID() + "@test.local")
                .passwordHash("irrelevant")
                .role(role)
                .build();
        User saved = userRepository.save(user);
        createdUserIds.add(saved.getId());
        return saved;
    }

    private UUID persistOrganization(UUID ownerId) {
        Organization organization = Organization.builder()
                .name("Waitlist Test Org " + UUID.randomUUID())
                .status(OrganizationStatus.APPROVED)
                .ownerId(ownerId)
                .documents(List.of())
                .build();
        Organization saved = organizationRepository.save(organization);
        createdOrgIds.add(saved.getId());
        return saved.getId();
    }

    private UUID persistEvent(UUID organizationId) {
        Instant startAt = Instant.now().plus(10, ChronoUnit.DAYS);
        Event event = Event.builder()
                .organizationId(organizationId)
                .title("Waitlist Test Event")
                .description("desc")
                .category("music")
                .status(EventStatus.PUBLISHED)
                .ticketPrefix("W" + UUID.randomUUID().toString().substring(0, 2).toUpperCase())
                .startAt(startAt)
                .endAt(startAt.plus(2, ChronoUnit.HOURS))
                .timezone("UTC")
                .build();
        Event saved = eventRepository.save(event);
        createdEventIds.add(saved.getId());
        return saved.getId();
    }

    private UUID persistTicketType(UUID eventId, int quantityAvailable) {
        TicketType tt = TicketType.builder()
                .eventId(eventId)
                .name("GA")
                .kind(TicketTypeKind.GENERAL_ADMISSION)
                .price(Money.builder().amount(1000L).currency("USD").build())
                .quantityTotal(Math.max(quantityAvailable, 1))
                .quantityAvailable(quantityAvailable)
                .saleStartAt(Instant.now().minus(1, ChronoUnit.DAYS))
                .saleEndAt(Instant.now().plus(5, ChronoUnit.DAYS))
                .maxPerOrder(10)
                .build();
        TicketType saved = ticketTypeRepository.save(tt);
        createdTicketTypeIds.add(saved.getId());
        return saved.getId();
    }

    // ---- POST /events/{eventId}/waitlist — sold-out gate (BR-WAIT-001) ----

    @Test
    void join_specificTicketType_soldOut_returns201_withPositionOne() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        UUID ticketTypeId = persistTicketType(eventId, 0);
        User buyer = persistUser(Role.CUSTOMER);
        String token = jwtService.generateAccessToken(buyer);

        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + token)
                        .contentType("application/json")
                        .content("{\"ticketTypeId\":\"" + ticketTypeId + "\"}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.eventId").value(eventId.toString()))
                .andExpect(jsonPath("$.ticketTypeId").value(ticketTypeId.toString()))
                .andExpect(jsonPath("$.userId").value(buyer.getId().toString()))
                .andExpect(jsonPath("$.position").value(1))
                .andExpect(jsonPath("$.notifiedAt").doesNotExist())
                .andExpect(jsonPath("$.offerExpiresAt").doesNotExist());

        List<WaitlistEntry> rows = waitlistEntryRepository.findAll().stream()
                .filter(e -> e.getEventId().equals(eventId)).toList();
        assertThat(rows).hasSize(1);
        rows.forEach(r -> createdWaitlistEntryIds.add(r.getId()));
    }

    @Test
    void join_specificTicketType_notSoldOut_returns409() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        UUID ticketTypeId = persistTicketType(eventId, 5); // still has availability
        User buyer = persistUser(Role.CUSTOMER);
        String token = jwtService.generateAccessToken(buyer);

        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + token)
                        .contentType("application/json")
                        .content("{\"ticketTypeId\":\"" + ticketTypeId + "\"}"))
                .andExpect(status().isConflict());
    }

    @Test
    void join_eventGeneral_allTicketTypesSoldOut_returns201() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        persistTicketType(eventId, 0);
        persistTicketType(eventId, 0);
        User buyer = persistUser(Role.CUSTOMER);
        String token = jwtService.generateAccessToken(buyer);

        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + token)
                        .contentType("application/json")
                        .content("{}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.ticketTypeId").doesNotExist())
                .andExpect(jsonPath("$.position").value(1));

        waitlistEntryRepository.findAll().stream()
                .filter(e -> e.getEventId().equals(eventId))
                .forEach(e -> createdWaitlistEntryIds.add(e.getId()));
    }

    @Test
    void join_eventGeneral_oneTicketTypeStillAvailable_returns409() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        persistTicketType(eventId, 0);
        persistTicketType(eventId, 3); // not sold out
        User buyer = persistUser(Role.CUSTOMER);
        String token = jwtService.generateAccessToken(buyer);

        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + token)
                        .contentType("application/json")
                        .content("{}"))
                .andExpect(status().isConflict());
    }

    @Test
    void join_eventGeneral_noTicketTypesAtAll_returns409() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        User buyer = persistUser(Role.CUSTOMER);
        String token = jwtService.generateAccessToken(buyer);

        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + token)
                        .contentType("application/json")
                        .content("{}"))
                .andExpect(status().isConflict());
    }

    @Test
    void join_unknownEvent_returns404() throws Exception {
        User buyer = persistUser(Role.CUSTOMER);
        String token = jwtService.generateAccessToken(buyer);

        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", UUID.randomUUID())
                        .header("Authorization", "Bearer " + token)
                        .contentType("application/json")
                        .content("{}"))
                .andExpect(status().isNotFound());
    }

    @Test
    void join_noToken_returns401() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        persistTicketType(eventId, 0);

        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .contentType("application/json")
                        .content("{}"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void join_sameUserTwice_secondAttemptReturns409() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        UUID ticketTypeId = persistTicketType(eventId, 0);
        User buyer = persistUser(Role.CUSTOMER);
        String token = jwtService.generateAccessToken(buyer);

        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + token)
                        .contentType("application/json")
                        .content("{\"ticketTypeId\":\"" + ticketTypeId + "\"}"))
                .andExpect(status().isCreated());
        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + token)
                        .contentType("application/json")
                        .content("{\"ticketTypeId\":\"" + ticketTypeId + "\"}"))
                .andExpect(status().isConflict());

        waitlistEntryRepository.findAll().stream()
                .filter(e -> e.getEventId().equals(eventId))
                .forEach(e -> createdWaitlistEntryIds.add(e.getId()));
    }

    // ---- Position sequence across real, sequential joiners (BR-WAIT-002 position math) ----

    @Test
    void join_positionSequence_multipleUsersJoinSameWaitlist_getSequentialPositions() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        UUID ticketTypeId = persistTicketType(eventId, 0);

        for (int expectedPosition = 1; expectedPosition <= 3; expectedPosition++) {
            User buyer = persistUser(Role.CUSTOMER);
            String token = jwtService.generateAccessToken(buyer);
            mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                            .header("Authorization", "Bearer " + token)
                            .contentType("application/json")
                            .content("{\"ticketTypeId\":\"" + ticketTypeId + "\"}"))
                    .andExpect(status().isCreated())
                    .andExpect(jsonPath("$.position").value(expectedPosition));
        }

        waitlistEntryRepository.findAll().stream()
                .filter(e -> e.getEventId().equals(eventId))
                .forEach(e -> createdWaitlistEntryIds.add(e.getId()));
    }

    @Test
    void join_positionScopedIndependently_specificTicketTypeVsEventGeneral_bothStartAtOne() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        UUID gaTicketTypeId = persistTicketType(eventId, 0);
        UUID vipTicketTypeId = persistTicketType(eventId, 0);
        User userA = persistUser(Role.CUSTOMER);
        User userB = persistUser(Role.CUSTOMER);
        String tokenA = jwtService.generateAccessToken(userA);
        String tokenB = jwtService.generateAccessToken(userB);

        // User A joins the GA-specific waitlist -> position 1 in that scope.
        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + tokenA)
                        .contentType("application/json")
                        .content("{\"ticketTypeId\":\"" + gaTicketTypeId + "\"}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.position").value(1));

        // User B joins the VIP-specific waitlist (different scope, same event) -> also position 1.
        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + tokenB)
                        .contentType("application/json")
                        .content("{\"ticketTypeId\":\"" + vipTicketTypeId + "\"}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.position").value(1));

        waitlistEntryRepository.findAll().stream()
                .filter(e -> e.getEventId().equals(eventId))
                .forEach(e -> createdWaitlistEntryIds.add(e.getId()));
    }

    // ---- GET /users/me/waitlist-entries — SecurityConfig matcher + own-entries-only visibility ----

    @Test
    void listMyEntries_noToken_returns401() throws Exception {
        mockMvc.perform(get("/api/v1/users/me/waitlist-entries"))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void listMyEntries_authenticatedNonAdminUser_returns200_notForbidden() throws Exception {
        User buyer = persistUser(Role.CUSTOMER);
        String token = jwtService.generateAccessToken(buyer);

        mockMvc.perform(get("/api/v1/users/me/waitlist-entries")
                        .header("Authorization", "Bearer " + token))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray());
    }

    @Test
    void listMyEntries_returnsOnlyCallersOwnEntries_oldestJoinedFirst() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        UUID ticketTypeAId = persistTicketType(eventId, 0);
        UUID ticketTypeBId = persistTicketType(eventId, 0);
        User caller = persistUser(Role.CUSTOMER);
        User otherUser = persistUser(Role.CUSTOMER);
        String callerToken = jwtService.generateAccessToken(caller);
        String otherToken = jwtService.generateAccessToken(otherUser);

        // Caller joins two different waitlists (oldest first).
        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + callerToken)
                        .contentType("application/json")
                        .content("{\"ticketTypeId\":\"" + ticketTypeAId + "\"}"))
                .andExpect(status().isCreated());
        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + callerToken)
                        .contentType("application/json")
                        .content("{\"ticketTypeId\":\"" + ticketTypeBId + "\"}"))
                .andExpect(status().isCreated());
        // A different user also joins one of the same waitlists - must never leak into caller's list.
        mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                        .header("Authorization", "Bearer " + otherToken)
                        .contentType("application/json")
                        .content("{\"ticketTypeId\":\"" + ticketTypeAId + "\"}"))
                .andExpect(status().isCreated());

        mockMvc.perform(get("/api/v1/users/me/waitlist-entries")
                        .header("Authorization", "Bearer " + callerToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].ticketTypeId").value(ticketTypeAId.toString()))
                .andExpect(jsonPath("$[0].userId").value(caller.getId().toString()))
                .andExpect(jsonPath("$[1].ticketTypeId").value(ticketTypeBId.toString()))
                .andExpect(jsonPath("$[1].userId").value(caller.getId().toString()));

        waitlistEntryRepository.findAll().stream()
                .filter(e -> e.getEventId().equals(eventId))
                .forEach(e -> createdWaitlistEntryIds.add(e.getId()));
    }

    // ---- Genuine concurrency: two threads racing to join the SAME (event, ticketType) scope ----

    @Test
    void join_concurrentJoinsForSameScope_neverCollideOnPosition_allPositionsSequentialAndUnique() throws Exception {
        UUID orgId = persistOrganization(UUID.randomUUID());
        UUID eventId = persistEvent(orgId);
        UUID ticketTypeId = persistTicketType(eventId, 0);

        int threadCount = 8;
        List<String> tokens = new ArrayList<>();
        for (int i = 0; i < threadCount; i++) {
            User buyer = persistUser(Role.CUSTOMER);
            tokens.add(jwtService.generateAccessToken(buyer));
        }

        CountDownLatch startLatch = new CountDownLatch(1);
        ExecutorService executor = Executors.newFixedThreadPool(threadCount);
        try {
            List<Callable<Integer>> tasks = IntStream.range(0, threadCount)
                    .<Callable<Integer>>mapToObj(i -> () -> {
                        startLatch.await();
                        return mockMvc.perform(post("/api/v1/events/{eventId}/waitlist", eventId)
                                        .header("Authorization", "Bearer " + tokens.get(i))
                                        .contentType("application/json")
                                        .content("{\"ticketTypeId\":\"" + ticketTypeId + "\"}"))
                                .andReturn().getResponse().getStatus();
                    })
                    .collect(Collectors.toList());

            List<Future<Integer>> futures = tasks.stream().map(executor::submit).collect(Collectors.toList());
            startLatch.countDown();

            List<Integer> statuses = new ArrayList<>();
            for (Future<Integer> f : futures) {
                statuses.add(f.get(30, TimeUnit.SECONDS));
            }
            assertThat(statuses).as("every concurrent join for a brand-new scope must succeed (201), got %s", statuses)
                    .allMatch(status -> status == 201);
        } finally {
            executor.shutdown();
        }

        List<WaitlistEntry> rows = waitlistEntryRepository.findAll().stream()
                .filter(e -> e.getEventId().equals(eventId)).toList();
        rows.forEach(r -> createdWaitlistEntryIds.add(r.getId()));

        assertThat(rows).hasSize(threadCount);
        Set<Integer> positions = rows.stream().map(WaitlistEntry::getPosition).collect(Collectors.toSet());
        assertThat(positions)
                .as("no two concurrent joiners for the same scope may land on the same position (V17 unique index + retry loop)")
                .hasSize(threadCount)
                .isEqualTo(IntStream.rangeClosed(1, threadCount).boxed().collect(Collectors.toSet()));
    }
}
